<?xml version="1.0" encoding="UTF-8"?><testrun name="HsqldbUserDaoTest" project="UM" tests="2" started="2" failures="0" errors="2" ignored="0">
  <testsuite name="UM.malykhin.nure.db.HsqldbUserDaoTest" time="0.112" displayname="HsqldbUserDaoTest" uniqueid="[engine:junit-vintage]/[runner:UM.malykhin.nure.db.HsqldbUserDaoTest]">
    <testcase name="testFindAll" classname="UM.malykhin.nure.db.HsqldbUserDaoTest" time="0.107" displayname="testFindAll" uniqueid="[engine:junit-vintage]/[runner:UM.malykhin.nure.db.HsqldbUserDaoTest]/[test:testFindAll(UM.malykhin.nure.db.HsqldbUserDaoTest)]">
      <error>UM.malykhin.nure.db.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@8f1a7cbd[file =C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck, exists=true, locked=false, valid=false, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck] is presumably locked by another process.&#13;
	at UM.malykhin.nure.db.ConnectionFactoryImpl.createConnection(ConnectionFactoryImpl.java:31)&#13;
	at UM.malykhin.nure.db.HsqldbUserDaoTest.getConnection(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:84)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at UM.malykhin.nure.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:28)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)&#13;
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)&#13;
	at java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)&#13;
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@8f1a7cbd[file =C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck, exists=true, locked=false, valid=false, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck] is presumably locked by another process.&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.jdbcConnection.&lt;init&gt;(Unknown Source)&#13;
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)&#13;
	at org.hsqldb.jdbcDriver.connect(Unknown Source)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at UM.malykhin.nure.db.ConnectionFactoryImpl.createConnection(ConnectionFactoryImpl.java:29)&#13;
	... 38 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testCreate" classname="UM.malykhin.nure.db.HsqldbUserDaoTest" time="0.005" displayname="testCreate" uniqueid="[engine:junit-vintage]/[runner:UM.malykhin.nure.db.HsqldbUserDaoTest]/[test:testCreate(UM.malykhin.nure.db.HsqldbUserDaoTest)]">
      <error>UM.malykhin.nure.db.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@8f1a7cbd[file =C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck, exists=true, locked=false, valid=false, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck] is presumably locked by another process.&#13;
	at UM.malykhin.nure.db.ConnectionFactoryImpl.createConnection(ConnectionFactoryImpl.java:31)&#13;
	at UM.malykhin.nure.db.HsqldbUserDaoTest.getConnection(HsqldbUserDaoTest.java:61)&#13;
	at org.dbunit.DatabaseTestCase.executeOperation(DatabaseTestCase.java:84)&#13;
	at org.dbunit.DatabaseTestCase.setUp(DatabaseTestCase.java:104)&#13;
	at UM.malykhin.nure.db.HsqldbUserDaoTest.setUp(HsqldbUserDaoTest.java:28)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:139)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)&#13;
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)&#13;
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)&#13;
	at java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)&#13;
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@8f1a7cbd[file =C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck, exists=true, locked=false, valid=false, fl =null]: java.lang.Exception: checkHeartbeat(): lock file [C:\Users\atom5\eclipse-workspace\UM\db\usermanagement.lck] is presumably locked by another process.&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.jdbcConnection.&lt;init&gt;(Unknown Source)&#13;
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)&#13;
	at org.hsqldb.jdbcDriver.connect(Unknown Source)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at java.sql.DriverManager.getConnection(Unknown Source)&#13;
	at UM.malykhin.nure.db.ConnectionFactoryImpl.createConnection(ConnectionFactoryImpl.java:29)&#13;
	... 38 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
